name: Build LaTeX document
on: pull_request
jobs:
  build-artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: main.tex
          working_directory: article/
          continue_on_error: true
      - name: Save PDF as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: main
          path: article/main.pdf
      - name: download artifact
        uses: actions/download-artifact@v3
        with:
          name: main
      - name: comment PR
        uses: tonyhallett/artifacts-url-comments@v1.1.0
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
              prefix: Segue o pdf
              suffix: Valeo
              format: name
              addTo: pullandissues
